<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\KolayYazdir.Core\KolayYazdir.Core.csproj" />
    <ProjectReference Include="..\KolayYazdir.Documents\KolayYazdir.Documents.csproj" />
    <ProjectReference Include="..\KolayYazdir.Printing\KolayYazdir.Printing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>KolayYazdir</AssemblyName>
    <Version>1.0.0</Version>
    <ApplicationIcon>Assets\kolay-yazdir.ico</ApplicationIcon>
    <ApplicationTitle>Kolay Yazdır</ApplicationTitle>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\kolay-yazdir.ico" />
    <Resource Include="Assets\Fonts\Montserrat-Regular.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-Medium.ttf" />
    <Resource Include="Assets\Fonts\Montserrat-SemiBold.ttf" />
  </ItemGroup>

</Project>
